# Generated by Django 4.2.8 on 2023-12-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='transaction_id',
        ),
    ]
