# Generated by Django 4.2.8 on 2023-12-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_payment_id_payment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='payment_id',
        ),
    ]
